// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRLab.Infrastructure.DB.Context;

#nullable disable

namespace PRLab.Infrastructure.DB.Migrations
{
    [DbContext(typeof(PRLabPgDBContext))]
    [Migration("20260609053607_AddExerciseTable")]
    partial class AddExerciseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovementEquipmentRequirement", b =>
                {
                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("MovementId", "EquipmentId", "GroupKey", "Kind");

                    b.HasIndex("EquipmentId");

                    b.ToTable("MovementEquipmentRequirement", "public");
                });

            modelBuilder.Entity("MovementPatternTag", b =>
                {
                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pattern")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("MovementId", "Pattern");

                    b.HasIndex("Pattern");

                    b.ToTable("MovementPatternTag", "public");
                });

            modelBuilder.Entity("PRLab.Application.Models.DB.Seeding.SeedHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("SeedHistory", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Description", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultLanguageCode");

                    b.ToTable("Descriptions", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Equipment", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Exercise", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MovementCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PrimaryPattern")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("VariantOfId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("MovementCategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("PrimaryPattern");

                    b.HasIndex("VariantOfId");

                    b.ToTable("Movement", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.MovementCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseMovementCategory")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("BaseMovementCategory");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("MovementCategory", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Muscle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BodySection")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LatinName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("BodySection");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("LatinName");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Muscle", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Role");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.DescriptionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("DescriptionId", "LanguageCode")
                        .IsUnique();

                    b.HasIndex("LanguageCode", "Content");

                    b.ToTable("DescriptionTranslations", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.MovementMuscle", b =>
                {
                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("MovementId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.HasIndex("Role");

                    b.ToTable("MovementMuscle", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.MuscleAntagonist", b =>
                {
                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntagonistMuscleId")
                        .HasColumnType("uuid");

                    b.HasKey("MuscleId", "AntagonistMuscleId");

                    b.HasIndex("AntagonistMuscleId");

                    b.ToTable("MuscleAntagonist", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Value.ExerciseBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MovementId");

                    b.HasIndex("ExerciseId", "Sequence")
                        .IsUnique();

                    b.ToTable("ExerciseBlock", "public");
                });

            modelBuilder.Entity("MovementEquipmentRequirement", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRLab.Domain.Model.Entity.Movement", null)
                        .WithMany("EquipmentRequirements")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("MovementPatternTag", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Movement", null)
                        .WithMany("Patterns")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Equipment", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("EquipmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("EquipmentId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("Equipment", "public");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Exercise", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("ExerciseId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("Exercise", "public");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Movement", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRLab.Domain.Model.Entity.MovementCategory", "MovementCategory")
                        .WithMany()
                        .HasForeignKey("MovementCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRLab.Domain.Model.Entity.Movement", "VariantOf")
                        .WithMany("Variants")
                        .HasForeignKey("VariantOfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MovementId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("MovementId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("Movement", "public");

                            b1.WithOwner()
                                .HasForeignKey("MovementId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Description");

                    b.Navigation("MovementCategory");

                    b.Navigation("VariantOf");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.MovementCategory", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MovementCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("MovementCategoryId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("MovementCategory", "public");

                            b1.WithOwner()
                                .HasForeignKey("MovementCategoryId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Muscle", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MuscleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("MuscleId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("Muscle", "public");

                            b1.WithOwner()
                                .HasForeignKey("MuscleId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.User", b =>
                {
                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("UserId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("Users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.DescriptionTranslation", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", null)
                        .WithMany("Translations")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.MovementMuscle", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Movement", "Movement")
                        .WithMany("Muscles")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRLab.Domain.Model.Entity.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.MuscleAntagonist", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Muscle", "AntagonistMuscle")
                        .WithMany()
                        .HasForeignKey("AntagonistMuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRLab.Domain.Model.Entity.Muscle", "Muscle")
                        .WithMany("Antagonists")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AntagonistMuscle");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("PRLab.Domain.Value.ExerciseBlock", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Exercise", null)
                        .WithMany("Blocks")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRLab.Domain.Model.Entity.Movement", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PRLab.Domain.Value.RestTarget", "RestBetweenReps", b1 =>
                        {
                            b1.Property<Guid>("ExerciseBlockId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Seconds")
                                .HasColumnType("integer");

                            b1.HasKey("ExerciseBlockId");

                            b1.ToTable("ExerciseBlock", "public");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseBlockId");
                        });

                    b.OwnsOne("PRLab.Domain.Value.RestTarget", "TransitionAfterBlock", b1 =>
                        {
                            b1.Property<Guid>("ExerciseBlockId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Seconds")
                                .HasColumnType("integer");

                            b1.HasKey("ExerciseBlockId");

                            b1.ToTable("ExerciseBlock", "public");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseBlockId");
                        });

                    b.OwnsOne("PRLab.Domain.Value.LoadTarget", "LoadTarget", b1 =>
                        {
                            b1.Property<Guid>("ExerciseBlockId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Unit")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<decimal?>("Value")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.HasKey("ExerciseBlockId");

                            b1.ToTable("ExerciseBlock", "public");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseBlockId");
                        });

                    b.OwnsOne("PRLab.Domain.Value.RepExecutionDetails", "ExecutionDetails", b1 =>
                        {
                            b1.Property<Guid>("ExerciseBlockId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BottomIntent")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<int?>("BottomPauseSeconds")
                                .HasColumnType("integer");

                            b1.Property<string>("ConcentricIntent")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<int?>("ConcentricSeconds")
                                .HasColumnType("integer");

                            b1.Property<string>("EccentricIntent")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<int?>("EccentricSeconds")
                                .HasColumnType("integer");

                            b1.Property<string>("Intent")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("TopIntent")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<int?>("TopPauseSeconds")
                                .HasColumnType("integer");

                            b1.HasKey("ExerciseBlockId");

                            b1.ToTable("ExerciseBlock", "public");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseBlockId");
                        });

                    b.OwnsOne("PRLab.Domain.Value.WorkTarget", "Target", b1 =>
                        {
                            b1.Property<Guid>("ExerciseBlockId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TargetType")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<decimal>("Value")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.HasKey("ExerciseBlockId");

                            b1.ToTable("ExerciseBlock", "public");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseBlockId");
                        });

                    b.Navigation("ExecutionDetails")
                        .IsRequired();

                    b.Navigation("LoadTarget")
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("RestBetweenReps")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();

                    b.Navigation("TransitionAfterBlock")
                        .IsRequired();
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Description", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Exercise", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Movement", b =>
                {
                    b.Navigation("EquipmentRequirements");

                    b.Navigation("Muscles");

                    b.Navigation("Patterns");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Muscle", b =>
                {
                    b.Navigation("Antagonists");
                });
#pragma warning restore 612, 618
        }
    }
}
