// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRLab.Infrastructure.DB.Context;

#nullable disable

namespace PRLab.Infrastructure.DB.Migrations
{
    [DbContext(typeof(PRLabPgDBContext))]
    partial class PRLabPgDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Description", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultLanguageCode");

                    b.ToTable("Descriptions", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Equipment", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.MovementCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseMovementCategory")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("BaseMovementCategory");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("MovementCategory", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Muscle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BodySection")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LatinName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("BodySection");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("LatinName");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Muscle", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Role");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.DescriptionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("DescriptionId", "LanguageCode")
                        .IsUnique();

                    b.HasIndex("LanguageCode", "Content");

                    b.ToTable("DescriptionTranslations", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.MuscleAntagonist", b =>
                {
                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntagonistMuscleId")
                        .HasColumnType("uuid");

                    b.HasKey("MuscleId", "AntagonistMuscleId");

                    b.HasIndex("AntagonistMuscleId");

                    b.ToTable("MuscleAntagonist", "public");
                });

            modelBuilder.Entity("PRLab.Infrastructure.DB.Seeding.SeedHistory", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("SeedHistory", "public");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Equipment", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("EquipmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("EquipmentId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("Equipment", "public");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.MovementCategory", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MovementCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("MovementCategoryId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("MovementCategory", "public");

                            b1.WithOwner()
                                .HasForeignKey("MovementCategoryId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Muscle", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MuscleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("MuscleId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("Muscle", "public");

                            b1.WithOwner()
                                .HasForeignKey("MuscleId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.User", b =>
                {
                    b.OwnsOne("PRLab.Domain.Value.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("UserId");

                            b1.HasIndex("IsDeleted");

                            b1.ToTable("Users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.DescriptionTranslation", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Description", null)
                        .WithMany("Translations")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRLab.Domain.Model.Join.MuscleAntagonist", b =>
                {
                    b.HasOne("PRLab.Domain.Model.Entity.Muscle", "AntagonistMuscle")
                        .WithMany()
                        .HasForeignKey("AntagonistMuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRLab.Domain.Model.Entity.Muscle", "Muscle")
                        .WithMany("Antagonists")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AntagonistMuscle");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Description", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PRLab.Domain.Model.Entity.Muscle", b =>
                {
                    b.Navigation("Antagonists");
                });
#pragma warning restore 612, 618
        }
    }
}
